In [1]:
s = "Hi there Logu!"

In [2]:
s.split(" ")

['Hi', 'there', 'Logu!']

2.use format()to print the string

In [3]:
planet = "moon"
diameter =  3474.8

In [4]:
print("the diameter of the {}is{}kilometers".format (planet,diameter))

the diameter of the moonis3474.8kilometers


3.nest dictionary grab the world "hello"


In [6]:
d = {"k1":[1,2,3,{"tricky":["oh","man","inception",{"target":[1,2,3,"hello"]}]}]}

In [7]:
d["k1"][3]["tricky"][3]["target"][3]

'hello'

4.numpy

In [17]:
import numpy as np

4.1. create an array of 10 zeroes ?

4.2. create an array of 10 fives ?

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

2. create an array of all the even integers from 20 to 35?


In [25]:
np.arange(20,35,2)

array([20, 22, 24, 26, 28, 30, 32, 34])

1. create a 3*3 matrix with values ranging from 0 to 8

In [27]:
np.arange (0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3.concatenates a and b

a=np.array ([4,5,6]),b=np.array([7,3,8])

In [47]:
a=np.array([4,5,6])
b=np.array([7,3,8])

In [48]:
np.concatenate((a,b))

array([4, 5, 6, 7, 3, 8])

pandas

5. create a dataframe with 3 rows and 2 columns.

In [38]:
import pandas as pd

In [40]:
data = np.arange(0,6).reshape(3,2)
df = pd.DataFrame(data)
df

0  1
0  0  1
1  2  3
2  4  5

6. generate the series of dates from 1st jan,2022 to 17th apr ,2022

In [49]:
df=pd.date_range(start="1/1/22",end="17/4/22")
df

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10',
               ...
               '2022-04-08', '2022-04-09', '2022-04-10', '2022-04-11',
               '2022-04-12', '2022-04-13', '2022-04-14', '2022-04-15',
               '2022-04-16', '2022-04-17'],
              dtype='datetime64[ns]', length=107, freq='D')

7.create 2D list to DataFrame

In [44]:
lists=[[1, "xxx",22]],[[2,"yyy",25]],[[3,"zzz",24]]

In [45]:
df=pd.DataFrame(lists)

In [46]:
df

0
0  [1, xxx, 22]
1  [2, yyy, 25]
2  [3, zzz, 24]